Disambiguate binary signatures by filename too
JetBrains/teamcity-symbol-server pull request #7
Opened 2017-07-20 19:42 UTC by marc-groundctl

Binary signatures are not random, but are instead generated from the
build time and mapping size.  A fast build machine can easily build 2
binaries in the same second, which can cause them to both have the same
signature, which would prevent the symbol server from serving them both
up independently.  With this change, the binaries can have different
signatures and so will both be available.

This can be reproduced by building `f.msbuild` from the test repository at https://github.com/marc-groundctl/didactic-journey

2017-07-20 20:04 UTC, ghost requested changes
thank you for PR
please fix the following issues before i'll be able to merge it
1. lets preserve 'sign' attribute as is in BinaryGuidDumper, so sign field will not change its row semantic of not being unique for binaries
2. please avoid two consequent calls of 'myBuildMetadataStorage.getEntriesByKey' - this will led to performance problem when having big number of artifacts on the server
3. instead of this lets use Iterator in old 
 getMetadataEntry method in a more optimat way by checking if several elements are available
and use file name in this case to get valid element

2017-07-20 21:50 UTC, ghost approved these changes

2017-07-20 21:51 UTC, merged

2017-07-21 17:25 UTC, marc-groundctl commented
I don't think we can actually store multiple metadata entries with the same build id and guid.  The implementation of `addParameters` appears to store the parameters with `HashMap.put`, so later calls with the same guid would overwrite the data of earlier calls.  This could be fixed by changing the map to a type which allows duplicate keys, but I can't change this since that class is part of TeamCity, not this plugin.

Alternatively, we could go back to the sign attribute change.  This would require 2 calls to `getEntriesByKey` but since f2de99a halved the number of calls it would come out to the same total number of calls as before.

I think changing TeamCity to allow multiple metadata instances in a build with the same key is the better option, but that's probably more complicated and I can't do it.  If you'd prefer to not change TeamCity for this, I can redo the sign attribute change.

2017-07-24 08:57 UTC, ekoshkin commented
You are right getEntriesByKey method returns several entries only if build metadata with the same key was reported in several builds not in a single build.

2017-07-24 10:01 UTC, ekoshkin commented
Fixed in b714649d2ff886ac87f04bcab0ab9a0e17b88e47